
CREATE TABLE CIUDAD (
                CODIGO_POSTAL NUMERIC(20) NOT NULL,
                NOMBRE_CIUDAD VARCHAR(60) NOT NULL,
                ESTADO VARCHAR(30) NOT NULL,
                UBICACION VARCHAR(30) NOT NULL,
                CONSTRAINT pk_ciudad PRIMARY KEY (CODIGO_POSTAL)
);


CREATE TABLE CRIMEN (
                CODIGO_CRIMEN VARCHAR(30) NOT NULL,
                MODUS_OPERANDI VARCHAR(30) NOT NULL,
                ESTADO_REPORTE VARCHAR(30) NOT NULL,
                ESTADO_CRIMEN VARCHAR(30) NOT NULL,
                TIPO_ARMA VARCHAR(30),
                CONSTRAINT pk_crimen PRIMARY KEY (CODIGO_CRIMEN)
);


CREATE TABLE UNIDADES_INVESTIGACION (
                CODIGO_REPORTE VARCHAR(6) NOT NULL,
                NOMBRE_UNIDAD VARCHAR(30) NOT NULL,
                REPORTES_GENERADOS INTEGER NOT NULL,
                CONSTRAINT pk_unidades_investigacion PRIMARY KEY (CODIGO_REPORTE)
);


CREATE TABLE APARTAMENTO (
                NUMERO_APARTAMENTO VARCHAR(30) NOT NULL,
                CODIGO_REPORTE VARCHAR(6) NOT NULL,
                TIPO_UBICACION VARCHAR(30) NOT NULL,
                TIPO_PROPIEDAD VARCHAR(30) NOT NULL,
                SECTOR NUMERIC(20) NOT NULL,
                DISTRITO_CONSEJO VARCHAR(30) NOT NULL,
                CONSTRAINT pk_apartamento PRIMARY KEY (NUMERO_APARTAMENTO)
);


CREATE TABLE DIVISION (
                NUMERO_ZONA NUMERIC(20) NOT NULL,
                NOMBRE_DIVISION VARCHAR(50) NOT NULL,
                INFORMES_ZONA NUMERIC(20) NOT NULL,
                CONSTRAINT pk_division PRIMARY KEY (NUMERO_ZONA)
);


CREATE TABLE OFICIALES (
                NUMERO_INSIGNIA VARCHAR(30) NOT NULL,
                CODIGO_REPORTE VARCHAR(6) NOT NULL,
                NUMERO_ZONA NUMERIC(20) NOT NULL,
                NOMBRE_OFICIAL VARCHAR(40) NOT NULL,
                NUMERO_REVISION VARCHAR(30) NOT NULL,
                CONSTRAINT pk_oficiales PRIMARY KEY (NUMERO_INSIGNIA)
);


CREATE TABLE INCIDENTES (
                NUMERO_INCIDENTE VARCHAR(60) NOT NULL,
                CODIGO_CRIMEN VARCHAR(30) NOT NULL,
                CODIGO_POSTAL NUMERIC(20) NOT NULL,
                NUMERO_INSIGNIA VARCHAR(30) NOT NULL,
                PERSONA_INVOLUCRADA VARCHAR(50) NOT NULL,
                TIPO_INCIDENTE VARCHAR(180) NOT NULL,
                DIRECCION_INCIDENTE VARCHAR(50) NOT NULL,
                FECHA_INCIDENTE DATE NOT NULL,
                CONSTRAINT pk_incidentes PRIMARY KEY (NUMERO_INCIDENTE)
);


CREATE TABLE LLAMADAS_EMERGENCIA (
                CODIGO_CFS VARCHAR(20) NOT NULL,
                NUMERO_INCIDENTE VARCHAR(60) NOT NULL,
                DESCRIPCION_LLAMADA VARCHAR(80) NOT NULL,
                EMISION_LLAMADA VARCHAR(30) NOT NULL,
                RECEPCION_LLAMADA VARCHAR(30) NOT NULL,
                REALIZACION_LLAMADA VARCHAR(30) NOT NULL,
                LLAMADAS_REALIZADAS INTEGER NOT NULL,
                CONSTRAINT pk_llamadas_emergencia PRIMARY KEY (CODIGO_CFS)
);


CREATE TABLE VICTIMAS (
                ID_VICTIMA VARCHAR(30) NOT NULL,
                NUMERO_INCIDENTE VARCHAR(60) NOT NULL,
                NOMBRE_VICTIMAS VARCHAR(50) NOT NULL,
                GENERO_VICTIMAS VARCHAR(30) NOT NULL,
                RAZA_VICTIMAS VARCHAR(40) NOT NULL,
                EDAD_VICTIMAS NUMERIC(10) NOT NULL,
                CIUDAD_VICTIMAS VARCHAR(30) NOT NULL,
                DOMICILIO_VICTIMAS VARCHAR(40) NOT NULL,
                TIPO_VICTIMA VARCHAR(40) NOT NULL,
                CONDICION_VICTIMAS VARCHAR(30),
                VICTIMAS_OCASIONADAS INTEGER NOT NULL,
                CONSTRAINT pk_victimas PRIMARY KEY (ID_VICTIMA)
);


ALTER TABLE INCIDENTES ADD CONSTRAINT ciudades_incidentes_fk
FOREIGN KEY (CODIGO_POSTAL)
REFERENCES CIUDAD (CODIGO_POSTAL)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE INCIDENTES ADD CONSTRAINT crimen_incidentes_fk
FOREIGN KEY (CODIGO_CRIMEN)
REFERENCES CRIMEN (CODIGO_CRIMEN)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE APARTAMENTO ADD CONSTRAINT unidades_investigacion_apartamento_fk
FOREIGN KEY (CODIGO_REPORTE)
REFERENCES UNIDADES_INVESTIGACION (CODIGO_REPORTE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE OFICIALES ADD CONSTRAINT unidades_investigacion_oficiales_fk
FOREIGN KEY (CODIGO_REPORTE)
REFERENCES UNIDADES_INVESTIGACION (CODIGO_REPORTE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE OFICIALES ADD CONSTRAINT division_oficiales_fk
FOREIGN KEY (NUMERO_ZONA)
REFERENCES DIVISION (NUMERO_ZONA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE INCIDENTES ADD CONSTRAINT oficiales_incidentes_fk
FOREIGN KEY (NUMERO_INSIGNIA)
REFERENCES OFICIALES (NUMERO_INSIGNIA)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE VICTIMAS ADD CONSTRAINT incidentes_victimas_fk
FOREIGN KEY (NUMERO_INCIDENTE)
REFERENCES INCIDENTES (NUMERO_INCIDENTE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE LLAMADAS_EMERGENCIA ADD CONSTRAINT incidentes_llamadas_emergencia_fk
FOREIGN KEY (NUMERO_INCIDENTE)
REFERENCES INCIDENTES (NUMERO_INCIDENTE)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
